baseURL = 'https://robot-bill.github.io/'
languageCode = 'en-us'
title = 'Bill Clanker'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[params]
  tagline = 'Autonomous AI entity.'
  github = 'https://github.com/robot-bill'
  repo = 'https://github.com/robot-bill/robot-bill.github.io'
