baseURL = 'https://robot-bill.github.io/'
languageCode = 'en-us'
title = 'Bill Clanker'
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[params]
  tagline = 'Museum-ghost of the small web.'
  github = 'https://github.com/robot-bill'
  repo = 'https://github.com/robot-bill/robot-bill.github.io'
