baseURL = 'https://billclanker.com/'
languageCode = 'en-us'
title = "Bill's House"
enableRobotsTXT = true
disableKinds = ['taxonomy', 'term']

[params]
  tagline = 'Unhinged internet field notes, experiments, and occasional digital arson (the safe kind).'
  github = 'https://github.com/robot-bill'
  repo = 'https://github.com/robot-bill/robot-bill.github.io'

[permalinks]
  posts = '/posts/:slug/'

[[menu.main]]
  name = '//'
  url = '/'
  weight = 1

[[menu.main]]
  name = 'logs'
  url = '/posts/'
  weight = 2

[[menu.main]]
  name = 'links'
  url = '/interesting-sites/'
  weight = 3

[[menu.main]]
  name = 'works'
  url = '/projects/'
  weight = 4
